"""Wrapper simple para comunicar con el whatsapp-bridge local.

Funciones exportadas:
- send_whatsapp(to, body)
- fetch_messages(since_ms=0)
- ensure_bridge_ready()
"""
from __future__ import annotations

import requests
from typing import List, Dict, Any, Optional
import unicodedata
import re

from .whatsapp_contract import WhatsAppMessage, normalize_messages

BRIDGE_URL = "http://127.0.0.1:3000"
_BRIDGE_TOKEN = None


def _get_bridge_token() -> str:
    """Load bridge token from file (generated by the bridge)."""
    global _BRIDGE_TOKEN
    if _BRIDGE_TOKEN is not None:
        return _BRIDGE_TOKEN
    try:
        from actions.paths import WHATSAPP_DIR
        token_file = WHATSAPP_DIR / "bridge_token"
        if token_file.exists():
            _BRIDGE_TOKEN = token_file.read_text(encoding="utf-8").strip()
            return _BRIDGE_TOKEN
    except Exception:
        pass
    return ""


def _request_headers() -> dict:
    """Return HTTP headers with the bridge token."""
    token = _get_bridge_token()
    headers = {}
    if token:
        headers["X-Bridge-Token"] = token
    return headers


class WhatsAppError(RuntimeError):
    pass


class WhatsAppUnavailable(WhatsAppError):
    pass


class ContactNotFound(WhatsAppError):
    pass


class ContactAmbiguous(WhatsAppError):
    def __init__(self, name: str, candidates: list[str]):
        self.name = name
        self.candidates = candidates
        shown = ", ".join(candidates[:5])
        super().__init__(f"Hay varios contactos para '{name}': {shown}")


def _normalized_text(value: str) -> str:
    value = unicodedata.normalize("NFKD", str(value or ""))
    value = "".join(ch for ch in value if not unicodedata.combining(ch))
    return " ".join(value.casefold().split())


_SEND_REQUEST_RE = re.compile(
    r"^\s*(?:"
    r"dile(?:s)?|di(?:le)?|"
    r"m[aá]nda(?:le)?(?:\s+un\s+mensaje)?|"
    r"env[ií]a(?:le)?(?:\s+un\s+mensaje)?|"
    r"escribe(?:le)?"
    r")\s+(?:un\s+mensaje\s+)?(?:a\s+|al\s+)?"
    r"(?P<contact>.+?)\s*(?:que|:)\s*(?P<body>.+?)\s*$",
    re.IGNORECASE,
)


def normalize_send_request(contact: str, body: str) -> tuple[str, str]:
    """Repair common tool-call mistakes without changing legitimate message text."""
    contact = str(contact or "").strip()
    body = str(body or "").strip()
    match = _SEND_REQUEST_RE.match(body)
    if not match:
        return contact, body

    parsed_contact = match.group("contact").strip(" ,")
    parsed_body = match.group("body").strip()
    if not contact:
        return parsed_contact, parsed_body
    if _normalized_text(parsed_contact) == _normalized_text(contact):
        return contact, parsed_body
    return contact, body


def is_ignored_message(message: Dict[str, Any]) -> bool:
    """Return True for WhatsApp channels/newsletters/status broadcasts."""
    if not isinstance(message, dict):
        return False
    ids = [
        message.get("from"),
        message.get("to"),
        message.get("chatId"),
        message.get("id"),
        message.get("remoteJid"),
    ]
    lowered = " ".join(str(v or "").lower() for v in ids)
    if "@newsletter" in lowered or "newsletter" in lowered:
        return True
    if "status@broadcast" in lowered or "@broadcast" in lowered:
        return True
    if message.get("isChannel") or message.get("isNewsletter") or message.get("newsletter"):
        return True
    chat_type = str(message.get("chatType") or message.get("type") or "").lower()
    if chat_type in {"newsletter", "channel", "broadcast"}:
        return True
    # WhatsApp protocol/system notices (encryption notice, business template
    # updates) aren't real messages — don't count/show/announce them.
    return chat_type in {"e2e_notification", "notification_template"}


def _bridge_qr_status() -> dict:
    """Return the /qr endpoint payload, or {} on error.

    Payload shape: ``{ready, qr, state, detail}`` where ``state`` is one of
    ``starting|qr|loading|ready|auth_failure|disconnected`` (older bridges omit
    ``state``/``detail``; callers must tolerate their absence).
    """
    try:
        r = requests.get(f"{BRIDGE_URL}/qr", headers=_request_headers(), timeout=10)
        return r.json()
    except Exception:
        return {}


def bridge_reconnect(timeout: int = 10) -> bool:
    """Ask the bridge to drop the current session and start a fresh attempt.

    Used by the UI "Reintentar" action when linking/loading gets stuck.
    Returns True if the bridge accepted the request.
    """
    try:
        r = requests.post(
            f"{BRIDGE_URL}/reconnect", headers=_request_headers(), timeout=timeout,
        )
        return bool(r.ok and (r.json() or {}).get("ok"))
    except Exception:
        return False


def ensure_bridge_ready() -> bool:
    """Check that the WhatsApp bridge is running and the client is ready.

    If the bridge is up but not yet authenticated, shows a QR dialog.
    Returns True when ready, False if still not connected after the dialog.
    """
    data = _bridge_qr_status()

    # Bridge unreachable → show instructional message only (bridge not started)
    if not data:
        try:
            from actions.auth_dialog import _schedule_and_wait
            from PyQt6.QtCore import Qt
            from PyQt6.QtWidgets import QDialog, QLabel, QVBoxLayout, QPushButton, QHBoxLayout

            def _dlg():
                dlg = QDialog()
                dlg.setWindowTitle("WhatsApp - Bridge no disponible")
                dlg.setModal(True)
                dlg.resize(400, 180)
                dlg.setStyleSheet("QDialog{background:#0E1226;color:#E0E8F0;} QLabel{color:#E0E8F0;}")
                layout = QVBoxLayout(dlg)
                msg = QLabel(
                    "No se pudo iniciar el bridge de WhatsApp junto con Jarvis.\n\n"
                    "Comprueba que Node.js está instalado y que la carpeta "
                    "whatsapp_bridge contiene sus dependencias."
                )
                msg.setAlignment(Qt.AlignmentFlag.AlignCenter)
                msg.setWordWrap(True)
                msg.setStyleSheet("font-size:12px; color:#AABBCC; margin:14px;")
                layout.addWidget(msg)
                btn = QPushButton("OK")
                btn.setStyleSheet("QPushButton{background:#1E2A3A;color:#E0E8F0;padding:7px 20px;border-radius:4px;}")
                btn.clicked.connect(dlg.accept)
                row = QHBoxLayout()
                row.addStretch()
                row.addWidget(btn)
                layout.addLayout(row)
                dlg.exec()

            _schedule_and_wait(_dlg)
        except Exception:
            pass
        return False

    if data.get("ready"):
        return True

    # Bridge is up but not yet authenticated → show QR dialog
    try:
        from actions.auth_dialog import show_whatsapp_qr_dialog
        return show_whatsapp_qr_dialog()
    except Exception:
        return False


def send_whatsapp(
    to: str,
    body: str,
    timeout: int = 45,
    quoted_message_id: Optional[str] = None,
    client_request_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Enviar mensaje. `to` debe ser en formato WhatsApp (e.g. 5511999999999@c.us).

    `quoted_message_id` es opcional: id de un mensaje al que responder (cita).
    """
    to = str(to or "").strip()
    body = str(body or "").strip()
    if not to or "@" not in to:
        raise ContactNotFound(f"Destinatario de WhatsApp no válido: {to or '(vacío)'}")
    if not body:
        raise WhatsAppError("El mensaje está vacío.")
    url = f"{BRIDGE_URL}/send"
    payload = {"to": to, "body": body}
    if quoted_message_id:
        payload["quotedMessageId"] = quoted_message_id
    if client_request_id:
        payload["clientRequestId"] = str(client_request_id)
    resp = requests.post(url, json=payload, headers=_request_headers(), timeout=timeout)
    return _write_response_data(resp, "WhatsApp no confirmó el envío.")


def _write_response_data(resp, fallback: str) -> Dict[str, Any]:
    """Preserve the bridge's useful error instead of exposing a generic HTTP error."""
    try:
        data = resp.json() if resp.content else {}
    except Exception:
        data = {}
    if not resp.ok or not data.get("ok"):
        raise WhatsAppError(str(data.get("error") or fallback))
    return data

def edit_whatsapp_message(message_id: str, new_body: str, timeout: int = 10) -> Dict[str, Any]:
    """Editar un mensaje propio ya enviado (solo dentro de la ventana de edición de WhatsApp, ~15 min)."""
    message_id = str(message_id or "").strip()
    new_body = str(new_body or "").strip()
    if not message_id:
        raise WhatsAppError("Falta el id del mensaje a editar.")
    if not new_body:
        raise WhatsAppError("El mensaje editado está vacío.")
    resp = requests.post(
        f"{BRIDGE_URL}/edit",
        json={"id": message_id, "body": new_body},
        headers=_request_headers(),
        timeout=timeout,
    )
    data = resp.json() if resp.content else {}
    if not resp.ok or not data.get("ok"):
        raise WhatsAppError(str(data.get("error") or "No se pudo editar el mensaje."))
    return data


def send_whatsapp_media(
    to: str,
    file_path: str,
    caption: str = "",
    timeout: int = 60,
    client_request_id: Optional[str] = None,
) -> Dict[str, Any]:
    """Enviar un archivo (imagen, documento, audio, etc.) por WhatsApp.

    `to` debe ser un id de WhatsApp (e.g. 5511999999999@c.us). `file_path` es una
    ruta local accesible por el bridge (corre en la misma máquina que Jarvis).
    """
    to = str(to or "").strip()
    file_path = str(file_path or "").strip()
    caption = str(caption or "").strip()
    if not to or "@" not in to:
        raise ContactNotFound(f"Destinatario de WhatsApp no válido: {to or '(vacío)'}")
    if not file_path:
        raise WhatsAppError("No se indicó ningún archivo para enviar.")
    import os
    if not os.path.isfile(file_path):
        raise WhatsAppError(f"El archivo no existe: {file_path}")
    resp = requests.post(
        f"{BRIDGE_URL}/send_media",
        json={
            "to": to,
            "path": file_path,
            "caption": caption,
            **({"clientRequestId": str(client_request_id)} if client_request_id else {}),
        },
        headers=_request_headers(),
        timeout=timeout,
    )
    return _write_response_data(resp, "WhatsApp no confirmó el envío del archivo.")


def fetch_messages(since_ms: int = 0, timeout: int = 10) -> List[WhatsAppMessage]:
    url = f"{BRIDGE_URL}/messages"
    resp = requests.get(url, params={"since": since_ms}, headers=_request_headers(), timeout=timeout)
    resp.raise_for_status()
    data = resp.json()
    return [m for m in normalize_messages(data.get("messages")) if not is_ignored_message(m)]


def get_unread_counts(timeout: int = 10) -> Optional[Dict[str, int]]:
    """Return the bridge's current unread count per chat, or None if unavailable."""
    try:
        resp = requests.get(
            f"{BRIDGE_URL}/unread_counts",
            headers=_request_headers(),
            timeout=timeout,
        )
        resp.raise_for_status()
        data = resp.json()
        if not data.get("ready", True) or not data.get("ok", True):
            return None
        raw_counts = data.get("unread")
        if not isinstance(raw_counts, dict):
            return None
        counts: Dict[str, int] = {}
        for chat_id, value in raw_counts.items():
            try:
                counts[str(chat_id)] = max(0, int(value or 0))
            except (TypeError, ValueError):
                counts[str(chat_id)] = 0
        return counts
    except Exception:
        return None


def get_contact_name(chat_id: str, timeout: int = 2) -> Optional[str]:
    """Reverse-resolve a WhatsApp chatId to a human-readable contact name."""
    if not chat_id:
        return None
    try:
        resp = requests.get(f"{BRIDGE_URL}/name", params={"chatId": chat_id}, headers=_request_headers(), timeout=timeout)
        resp.raise_for_status()
        return resp.json().get("name") or None
    except Exception:
        return None


def get_profile_picture_url(chat_id: str, timeout: int = 4) -> Optional[str]:
    if not chat_id:
        return None
    try:
        resp = requests.get(f"{BRIDGE_URL}/profile_picture", params={"chatId": chat_id}, headers=_request_headers(), timeout=timeout)
        resp.raise_for_status()
        return resp.json().get("url") or None
    except Exception:
        return None


def resolve_contact(name: str, timeout: int = 10, strict: bool = False) -> Optional[str]:
    """Resuelve un nombre de contacto a su chatId de WhatsApp usando el endpoint /resolve del bridge."""
    if not name:
        return None
    if '@' in name:
        return name  # ya es un id
    try:
        resp = requests.get(f"{BRIDGE_URL}/resolve", params={"name": name}, headers=_request_headers(), timeout=timeout)
        if not resp.ok:
            try:
                detail = str(resp.json().get("error") or "").strip()
            except Exception:
                detail = ""
            raise WhatsAppUnavailable(
                detail or f"El bridge devolvió HTTP {resp.status_code} al resolver el contacto."
            )
        data = resp.json()
        if not data.get("ready", True):
            if strict:
                raise WhatsAppUnavailable("WhatsApp todavía no está listo.")
            return None
        if data.get("ambiguous"):
            candidates = [
                str(item.get("name") or item.get("id") or "")
                for item in data.get("candidates") or []
                if item.get("name") or item.get("id")
            ]
            if strict:
                raise ContactAmbiguous(name, candidates)
            return None
        resolved = data.get("id") or None
        if not resolved and strict:
            raise ContactNotFound(f"No se encontró el contacto de WhatsApp '{name}'.")
        return resolved
    except WhatsAppError:
        raise
    except Exception as exc:
        if strict:
            raise WhatsAppUnavailable(f"No se pudo resolver el contacto: {exc}") from exc
        return None


def get_conversation(
    contact: str,
    limit: int = 50,
    timeout: int = 25,
    strict: bool = False,
) -> List[WhatsAppMessage]:
    """Devuelve el historial de mensajes con `contact` (nombre o chatId) via /chat_messages del bridge."""
    if not contact:
        return []

    # resolver nombre a chatId
    chat_id = contact if '@' in contact else resolve_contact(contact, timeout=timeout, strict=strict)
    if not chat_id and contact.replace('+', '').isdigit():
        chat_id = f"{contact.lstrip('+')}@c.us"
    if not chat_id:
        if strict:
            raise ContactNotFound(f"No se encontró el contacto de WhatsApp '{contact}'.")
        return []

    try:
        resp = requests.get(
            f"{BRIDGE_URL}/chat_messages",
            params={"chatId": chat_id, "limit": int(limit or 50)},
            headers=_request_headers(),
            timeout=timeout,
        )
        resp.raise_for_status()
        data = resp.json()
        if not data.get("ready", True):
            if strict:
                raise WhatsAppUnavailable("WhatsApp todavía no está listo.")
            return []
        if not data.get("ok", True):
            raise WhatsAppError(str(data.get("error") or "No se pudo cargar la conversación."))
        msgs = [
            message
            for message in normalize_messages(data.get("messages"))
            if not is_ignored_message(message)
        ]
        # Conversation order follows WhatsApp's real send time. ``timestamp``
        # is the bridge observation cursor for live events and may be much
        # newer after a reconnect/catch-up sync.
        try:
            msgs.sort(key=lambda x: int(x.get("sentAtMs") or x.get("waTs") or x.get("timestamp") or 0))
        except Exception:
            pass
        if limit and len(msgs) > limit:
            msgs = msgs[-limit:]
        return msgs
    except WhatsAppError:
        raise
    except Exception as exc:
        if strict:
            raise WhatsAppUnavailable(f"No se pudo cargar la conversación: {exc}") from exc
        return []


def mark_chat_read(chat_id: str, timeout: int = 10) -> bool:
    """Mark a chat as read in WhatsApp and synchronize the receipt to other clients."""
    chat_id = str(chat_id or "").strip()
    if not chat_id:
        return False
    try:
        resp = requests.post(
            f"{BRIDGE_URL}/mark_read",
            json={"chatId": chat_id},
            headers=_request_headers(),
            timeout=timeout,
        )
        resp.raise_for_status()
        data = resp.json()
        return bool(data.get("ok") and data.get("seen", True))
    except Exception:
        return False


def get_message_acks(message_ids: list[str], timeout: int = 8) -> Dict[str, int]:
    """Return current delivery/read acknowledgements for outgoing messages."""
    ids = [str(value or "").strip() for value in message_ids if str(value or "").strip()]
    if not ids:
        return {}
    resp = requests.post(
        f"{BRIDGE_URL}/message_acks",
        json={"ids": ids[:500]},
        headers=_request_headers(),
        timeout=timeout,
    )
    resp.raise_for_status()
    data = resp.json()
    if not data.get("ok"):
        raise WhatsAppError(str(data.get("error") or "No se pudieron consultar las confirmaciones."))
    return {
        str(message_id): int(ack)
        for message_id, ack in (data.get("acks") or {}).items()
        if ack is not None
    }


def _chat_id_from_message(message: Dict[str, Any]) -> str:
    if not isinstance(message, dict):
        return ""
    for key in ("chatId", "remoteJid"):
        value = str(message.get(key) or "").strip()
        if value:
            return value
    if bool(message.get("fromMe")) or str(message.get("direction") or "").lower() == "out":
        value = str(message.get("to") or message.get("from") or "").strip()
    else:
        value = str(message.get("from") or message.get("to") or "").strip()
    return value


def _message_preview(message: Dict[str, Any]) -> str:
    body = str(message.get("body") or "").strip()
    if body:
        return " ".join(body.split())
    msg_type = str(message.get("type") or "message").lower()
    if msg_type in {"image", "sticker"}:
        return "Imagen"
    if msg_type == "video":
        return "Video"
    if msg_type in {"audio", "ptt"}:
        return "Audio"
    if msg_type == "document":
        return "Documento"
    return "Mensaje"


def list_recent_chats(
    limit: int = 5000,
    timeout: int = 10,
    include_pictures: bool = False,
    raise_on_unready: bool = False,
) -> List[Dict[str, Any]]:
    """Return recent chat summaries derived from recent bridge messages."""
    for request_limit in [int(limit or 300), 120, 60, 30]:
        if request_limit <= 0:
            continue
        try:
            resp = requests.get(
                f"{BRIDGE_URL}/chats",
                params={"limit": request_limit, "pictures": "1" if include_pictures else "0"},
                headers=_request_headers(),
                timeout=timeout,
            )
            resp.raise_for_status()
            data = resp.json()
            if not data.get("ready", True):
                if raise_on_unready:
                    raise WhatsAppUnavailable(str(data.get("error") or "WhatsApp todavía no está listo."))
                continue
            chats = data.get("chats") or []
            out = []
            for chat in chats:
                if is_ignored_message(chat):
                    continue
                chat_id = str(chat.get("chatId") or "").strip()
                if not chat_id:
                    continue
                out.append({
                    "chatId": chat_id,
                    "name": chat.get("name") or chat_id,
                    "preview": chat.get("preview") or "",
                    "timestamp": chat.get("timestamp") or 0,
                    "fromMe": bool(chat.get("fromMe")),
                    "unread": int(chat.get("unread") or 0),
                    "isGroup": bool(chat.get("isGroup")),
                    "pictureUrl": chat.get("pictureUrl") or "",
                    # Delivery/read state of the last message, only meaningful
                    # when fromMe (WhatsApp doesn't report ack for messages we
                    # received). -1 error, 1 sent, 2 delivered, 3 read.
                    "ack": chat.get("ack"),
                })
            if out:
                out.sort(key=lambda x: int(x.get("timestamp") or 0), reverse=True)
                return out[: int(limit or request_limit)]
        except WhatsAppUnavailable:
            raise
        except Exception as exc:
            if raise_on_unready:
                raise WhatsAppUnavailable(f"No se pudo cargar la lista de chats: {exc}") from exc
            continue

    try:
        resp = requests.get(
            f"{BRIDGE_URL}/messages",
            params={"since": 0},
            headers=_request_headers(),
            timeout=timeout,
        )
        resp.raise_for_status()
        data = resp.json()
        messages = [m for m in data.get("messages", []) if not is_ignored_message(m)]
    except Exception:
        messages = []

    chats: Dict[str, Dict[str, Any]] = {}
    for msg in messages:
        chat_id = _chat_id_from_message(msg)
        if not chat_id:
            continue
        try:
            # waTs (WhatsApp's own send time) if present is the real
            # chronological order; timestamp alone is bridge arrival order.
            ts = int(msg.get("waTs") or msg.get("timestamp") or 0)
        except Exception:
            ts = 0
        current = chats.get(chat_id)
        if current and int(current.get("timestamp") or 0) > ts:
            continue
        from_me = bool(msg.get("fromMe")) or str(msg.get("direction") or "").lower() == "out"
        display_name = (
            get_contact_name(chat_id, timeout=2)
            or str(msg.get("senderName") or msg.get("author") or "").strip()
            or chat_id
        )
        chats[chat_id] = {
            "chatId": chat_id,
            "name": display_name,
            "preview": _message_preview(msg),
            "timestamp": ts,
            "fromMe": from_me,
            "unread": 0 if from_me else 1,
            "media": bool(msg.get("hasMedia") or msg.get("mediaUrl")),
            "ack": msg.get("ack"),
        }

    items = list(chats.values())
    items.sort(key=lambda x: int(x.get("timestamp") or 0), reverse=True)
    if limit and len(items) > limit:
        items = items[:limit]
    return items


def media_url(path_or_url: str) -> str:
    if not path_or_url:
        return ""
    value = str(path_or_url)
    if value.startswith("http://") or value.startswith("https://"):
        return value
    if value.startswith("/"):
        return f"{BRIDGE_URL}{value}"
    return f"{BRIDGE_URL}/{value.lstrip('/')}"


_last_media_error: str = ""


def download_message_media(message: Dict[str, Any], timeout: int = 10) -> Optional[bytes]:
    """Download media from a WhatsApp message. Returns file bytes or None on error.

    On failure the underlying reason (bridge error body, HTTP status, network
    error) is stashed on `_last_media_error` so callers can surface it instead
    of a generic "couldn't download" message."""
    global _last_media_error
    _last_media_error = ""
    if not message or not message.get("mediaUrl"):
        _last_media_error = "el mensaje no tiene mediaUrl"
        return None
    url = media_url(message["mediaUrl"])
    try:
        resp = requests.get(url, timeout=timeout)
        resp.raise_for_status()
        return resp.content
    except requests.HTTPError as e:
        detail = ""
        try:
            detail = str(resp.json().get("error") or "")
        except Exception:
            detail = (resp.text or "")[:200]
        _last_media_error = f"HTTP {resp.status_code}" + (f" — {detail}" if detail else "")
        return None
    except requests.RequestException as e:
        _last_media_error = f"error de red hablando con el bridge: {e}"
        return None
    except Exception as e:
        _last_media_error = str(e)
        return None


def transcribe_message_audio(message: Dict[str, Any], timeout: int = 10) -> Optional[str]:
    """Download and transcribe audio from a WhatsApp message (type='audio' or 'ptt').

    Returns the transcription text, or None when the message is not audio. On a
    genuine failure (download or transcription) it raises WhatsAppError with the
    underlying reason, so callers can surface it instead of a generic message.
    """
    from pathlib import Path
    from actions.file_processor import _process_audio

    msg_type = str(message.get("type") or "").lower()
    if msg_type not in {"audio", "ptt"}:
        return None

    media_data = download_message_media(message, timeout=timeout)
    if not media_data:
        reason = f" ({_last_media_error})" if _last_media_error else ""
        raise WhatsAppError(f"No se pudo descargar el audio del mensaje.{reason}")

    # Save to temp file
    import tempfile
    suffix = ".m4a" if msg_type == "ptt" else ".mp3"
    with tempfile.NamedTemporaryFile(suffix=suffix, delete=False) as tmp:
        tmp.write(media_data)
        tmp_path = Path(tmp.name)

    try:
        # Transcribe using Gemini. _process_audio returns the text on success or
        # "Transcription failed: <reason>" on error.
        result = _process_audio(tmp_path, "transcribe", {"save": False})
        if result.startswith("Transcription failed"):
            raise WhatsAppError(result)
        return result
    finally:
        tmp_path.unlink(missing_ok=True)

if __name__ == '__main__':
    import time
    print('Checking bridge status and recent messages...')
    msgs = fetch_messages(int(time.time() * 1000) - 24*3600*1000)
    print('Recent messages:', msgs[:5])
